name: password_vault_app
description: A secure password vault application with modern UI design.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  
  # UI enhancements
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  
  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # The asset and font entries that caused the errors have been removed.
  # If you add these assets later, you'll need to uncomment and update these lines.
  # assets:
  #   - assets/animations/
  #   - assets/images/
  
  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/CustomIcons.ttf